version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: tutorbot-backend:latest
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=lecturevault
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=mydatabase
    depends_on:
      - postgres
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: tutorbot-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:8.2.2-noble
    environment:
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db

  postgres:
    image: pgvector/pgvector:pg15-trixie
    environment:
      POSTGRES_DB: lecturevault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  mongo-data:
  pgdata:
